name: Build FAISS Index

on:
  workflow_dispatch:   # Allow manual trigger
  push:
    paths:
      - 'data/**'
      - 'utils/**'
      - 'build_index.py'
      - 'requirements.txt'

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Environment Variables
      run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV

    - name: Build FAISS Index
      run: python build_index.py

    - name: Upload FAISS Index as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: recipe-faiss-index
        path: recipe_faiss_index/
