name: Run Streamlit App

on:
  workflow_dispatch:   # Allow manual trigger (you control it)

jobs:
  run-streamlit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install streamlit pyngrok

    - name: Set up Environment Variables
      run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV

    
    - name: Start Streamlit app and expose with ngrok
      run: |
         wget https://github.com/ngrok/ngrok/releases/download/v3.9.0/ngrok-v3-stable-linux-amd64.tgz
         tar -xvzf ngrok-v3-stable-linux-amd64.tgz
         export NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }}
         ./ngrok authtoken $NGROK_AUTH_TOKEN
         streamlit run app.py &
         sleep 10
         ./ngrok http 8501 &
         sleep 15
         curl http://localhost:4040/api/tunnels







