name: Run Streamlit App

on:
  workflow_dispatch:   # Allow manual trigger (you control it)

jobs:
  run-streamlit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install streamlit pyngrok

    - name: Set up Environment Variables
      run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV

    - name: Start Streamlit app with ngrok
      run: |
        echo "from pyngrok import ngrok" > expose.py
        echo "import os" >> expose.py
        echo "ngrok.set_auth_token(os.getenv('NGROK_AUTH_TOKEN'))" >> expose.py
        echo "public_url = ngrok.connect(8501)" >> expose.py
        echo "print('Public URL:', public_url)" >> expose.py
        streamlit run app.py & python3 expose.py
